In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("cars.csv")
df.shape

(299, 5)

In [19]:
df.head()

brand  km_driven    fuel         owner purchased
0   Maruti     145500  Diesel   First Owner        No
1    Skoda     120000  Diesel  Second Owner        No
2    Honda     140000  Petrol   Third Owner        No
3  Hyundai     127000  Diesel   First Owner        No
4   Maruti     120000  Petrol   First Owner        No

In [20]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner'], dtype=object)

# Ordinal Encoding

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
encoder.categories_

[array(['First Owner', 'Second Owner', 'Third Owner',
        'Fourth & Above Owner'], dtype=object)]

In [34]:
order = [['First Owner', 'Second Owner', 'Third Owner','Fourth & Above Owner']]
encoder = OrdinalEncoder(categories = order, handle_unknown = "use_encoded_value", unknown_value = 4)

In [35]:
encoder.fit(df['owner'].values.reshape(-1,1))

OrdinalEncoder(categories=[['First Owner', 'Second Owner', 'Third Owner',
                            'Fourth & Above Owner']],
               handle_unknown='use_encoded_value', unknown_value=4)

In [44]:
import numpy as np
data = np.array(['First Owner', 'Second Owner', 'Third Owner','Fourth & Above Owner' , 'fiveth'])
# np.unique(encoder.transform(df['owner'].values.reshape(-1,1)))
print(np.unique(encoder.transform(data.reshape(-1,1))))
encoder.transform(data.reshape(-1,1))

[0. 1. 2. 3. 4.]


array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

# Label Encoding

In [39]:
df['purchased'].unique()

array(['No', 'Yes', 'yes'], dtype=object)

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
le = LabelEncoder()

In [42]:
le.fit(df['purchased'].values.reshape(-1,1))

C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [43]:
le.transform(df['purchased'].values.reshape(-1,1) )

C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1])

In [45]:
le.classes_

array(['No', 'Yes', 'yes'], dtype=object)