In [5]:
import numpy as np
X = np.array (
    [ [1, 5],
      [2, -2],
      [3,  5465] ])
X

array([[   1,    5],
       [   2,   -2],
       [   3, 5465]])

# StandardScaler

In [2]:
from sklearn.preprocessing import StandardScaler

In [ ]:
!pip install scikit-learn

In [6]:
scaler = StandardScaler()

In [11]:
scaled_value = scaler.fit_transform(X)
scaled_value

array([[-1.22474487, -0.7057474 ],
       [ 0.        , -0.70846529],
       [ 1.22474487,  1.41421269]])

In [12]:
scaler.inverse_transform(scaled_value)

array([[ 1.000e+00,  5.000e+00],
       [ 2.000e+00, -2.000e+00],
       [ 3.000e+00,  5.465e+03]])

# MinMaxScaler

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler2 = MinMaxScaler()

In [9]:
scaler2.fit_transform(X)

array([[0.        , 0.00128041],
       [0.5       , 0.        ],
       [1.        , 1.        ]])